"""Even Fibonacci numbers.

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
our million, find the sum of the even-valued terms.
"""


def main():
    """Print sum of even valued terms of Fibonacci sequence (<4,000,000)."""
    current = 0
    a, b = 1, 2
    lst = []

    while current < 4_000_000:

        if b % 2 == 0:
            lst.append(b)

        a, b = b, a + b
        current = b

    print(sum(lst))


if __name__ == '__main__':
    main()
